import { Sparkles, RefreshCw, AlertCircle } from 'lucide-react';
import { Card, CardHeader, CardBody } from './Card';
import { Button } from './Button';

export const AISummary = ({ summary, loading, error, onGenerate }) => {
  if (error) {
    return (
      <Card className="border-red-200 dark:border-red-800">
        <CardBody>
          <div className="flex items-start gap-3">
            <AlertCircle size={20} className="text-red-600 mt-0.5 flex-shrink-0" />
            <div className="flex-1">
              <p className="text-red-700 dark:text-red-400 font-medium">
                Failed to generate AI summary
              </p>
              <p className="text-sm text-red-600 dark:text-red-500 mt-1">
                {error}
              </p>
              <Button
                size="sm"
                variant="ghost"
                onClick={onGenerate}
                className="mt-3 text-red-600"
              >
                <RefreshCw size={16} className="mr-2" />
                Try Again
              </Button>
            </div>
          </div>
        </CardBody>
      </Card>
    );
  }

  if (loading) {
    return (
      <Card className="border-purple-200 dark:border-purple-800">
        <CardBody>
          <div className="flex items-center gap-3">
            <Sparkles size={20} className="text-purple-600 animate-pulse" />
            <div className="flex-1">
              <p className="text-purple-700 dark:text-purple-400 font-medium">
                Generating AI Summary...
              </p>
              <p className="text-sm text-purple-600 dark:text-purple-500 mt-1">
                Analyzing progress, blockers, and key metrics
              </p>
            </div>
          </div>
        </CardBody>
      </Card>
    );
  }

  if (!summary) {
    return (
      <Card className="border-purple-200 dark:border-purple-800 bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20">
        <CardBody>
          <div className="flex items-start gap-3">
            <Sparkles size={24} className="text-purple-600 dark:text-purple-400 flex-shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-gray-900 dark:text-gray-100 mb-1">
                AI-Powered Insights
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                Get an AI-generated summary of progress, achievements, blockers, and recommended next steps based on all updates and key results.
              </p>
              <Button
                size="sm"
                onClick={onGenerate}
                className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700"
              >
                <Sparkles size={16} className="mr-2" />
                Generate AI Summary
              </Button>
            </div>
          </div>
        </CardBody>
      </Card>
    );
  }

  return (
    <Card className="border-purple-200 dark:border-purple-800">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles size={20} className="text-purple-600 dark:text-purple-400" />
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
              AI-Generated Summary
            </h3>
          </div>
          <Button
            size="sm"
            variant="ghost"
            onClick={onGenerate}
            className="text-purple-600"
          >
            <RefreshCw size={16} className="mr-2" />
            Regenerate
          </Button>
        </div>
      </CardHeader>
      <CardBody>
        <div className="prose prose-sm dark:prose-invert max-w-none">
          <div className="whitespace-pre-wrap text-gray-700 dark:text-gray-300 leading-relaxed">
            {summary}
          </div>
        </div>
        <div className="mt-4 pt-4 border-t border-gray-200 dark:border-gray-700">
          <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
            <Sparkles size={12} />
            Generated by AI • Based on recent updates and key results
          </p>
        </div>
      </CardBody>
    </Card>
  );
};
